version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
    labels:
      - "configuraciÃ³n"
      - "dependabot"
    target-branch: "master"
    open-pull-requests-limit: 5

    ignore:
      - dependency-name: org.junit:junit-bom
        versions:
          - ">= 6.0.0""
